<a href="https://colab.research.google.com/github/therishabhmittal-05/Pytorch/blob/main/pytorch_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
torch.__version__

'2.6.0+cu124'

In [ ]:
scalar = torch.tensor(2)
vector = torch.tensor([2,3])
matrix = torch.tensor([[[2,3,4,5],
                       [2,4,5,5],
                       [2, 5, 8, 3]],
                       [[2,3,4,5],
                       [2,4,5,5],
                       [2, 5, 8, 3]]])
matrix2 = torch.tensor([[2,3,4,5],
                       [2,4,5,5],
                       [2, 5, 8, 3]])

In [ ]:
scalar, vector, matrix, matrix2

(tensor(2),
 tensor([2, 3]),
 tensor([[[2, 3, 4, 5],
          [2, 4, 5, 5],
          [2, 5, 8, 3]],
 
         [[2, 3, 4, 5],
          [2, 4, 5, 5],
          [2, 5, 8, 3]]]),
 tensor([[2, 3, 4, 5],
         [2, 4, 5, 5],
         [2, 5, 8, 3]]))

In [ ]:
matrix2.shape

torch.Size([3, 4])

In [ ]:
matrix2.ndim

2

In [ ]:
matrix.size()

torch.Size([2, 3, 4])

In [ ]:
tensor0 = torch.rand(224, 224, 3)

In [ ]:
tensor0

tensor([[[0.3901, 0.4744, 0.6469],
         [0.2883, 0.8234, 0.1319],
         [0.1185, 0.8589, 0.5317],
         ...,
         [0.7063, 0.8068, 0.8197],
         [0.8348, 0.1410, 0.0794],
         [0.5827, 0.8935, 0.6484]],

        [[0.0919, 0.0261, 0.7432],
         [0.4585, 0.2762, 0.6133],
         [0.7441, 0.9021, 0.2436],
         ...,
         [0.0206, 0.3574, 0.2620],
         [0.9138, 0.7353, 0.0611],
         [0.8351, 0.8647, 0.5383]],

        [[0.9836, 0.5735, 0.4487],
         [0.1847, 0.5721, 0.4075],
         [0.5065, 0.0038, 0.1263],
         ...,
         [0.5418, 0.6300, 0.3232],
         [0.3081, 0.6086, 0.5068],
         [0.6569, 0.1819, 0.4524]],

        ...,

        [[0.2740, 0.9246, 0.9449],
         [0.2953, 0.5849, 0.3095],
         [0.2480, 0.4683, 0.9281],
         ...,
         [0.2300, 0.4332, 0.5453],
         [0.9808, 0.4714, 0.4051],
         [0.3037, 0.8456, 0.6908]],

        [[0.4637, 0.4611, 0.4390],
         [0.1931, 0.7355, 0.2152],
         [0.

In [ ]:
tensor0.shape, tensor0.size(), tensor0.ndim

(torch.Size([224, 224, 3]), torch.Size([224, 224, 3]), 3)

In [ ]:
tensor1 = torch.zeros_like(input = tensor0)

In [ ]:
tensor1

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
tensor2 = torch.arange(0, 10, 0.01)

In [ ]:
tensor2.ndim

1

In [ ]:
tensor3 = torch.rand(4,
                     dtype=torch.float16,
                     requires_grad=False,
                     device=None)
tensor3

tensor([0.7324, 0.4399, 0.1509, 0.8516], dtype=torch.float16)

In [ ]:
tensor3.shape, tensor3.ndim, tensor3.device, tensor3.dtype

(torch.Size([4]), 1, device(type='cpu'), torch.float16)

issues when dealing with Pytorch Tensor\
What, What, Where\
shape, datatype, device

# Tensor Operation
Addition\
Substraction\
Multiplication (element-wise)\
Division\
Matrix multiplication